sudo: required
services: docker
language: python
install:
  - pip install docker git+https://github.com/ansible/molecule.git openshift jmespath
script:
  - name: Test role
    stage: test
    script: molecule test
  - name: Test local (Kubernetes)
    script: molecule test -s test-local
  - name: Test cluster (OpenShift)
    env:
    - DEST_IMAGE=docker.io/fabianvf/game-server-operator:test
    - TEST_NAMESPACE=osdk-test
    - sudo sed -i -E 's/(^127.0.0.1.*)/\1 minecraft-osdk-test.127.0.0.1.nip.io' /etc/hosts
    before_script:
    - sudo service docker stop
    - sudo sed -i 's/DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry 172.30.0.0\/16 /' /etc/default/docker
    - sudo service docker start
    - curl -Lo oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    - tar xvzOf oc.tar.gz openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc > oc && chmod +x oc && sudo mv oc /usr/local/bin/
    - oc cluster up --base-dir=$HOME/oscluster
    - oc login -u system:admin
    - curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.4.0/operator-sdk-v0.4.0-x86_64-linux-gnu
    - chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin
    - sed -i "s|{{ REPLACE_IMAGE }}|$DEST_IMAGE|g" deploy/operator.yaml
    - sed -i 's|{{ pull_policy.default..Always.. }}|Never|g' deploy/operator.yaml
    - operator-sdk build --enable-tests "$DEST_IMAGE"
    - oc new-project ${TEST_NAMESPACE}
    - oc create -f "deploy/service_account.yaml"
    - oc create -f "deploy/role.yaml"
    - oc create -f "deploy/role_binding.yaml"
    - oc create -f "deploy/crds/apps_v1alpha1_minecraft.yaml"
    script: operator-sdk test cluster --service-account minecraft-operator --image-pull-policy Never --namespace ${TEST_NAMESPACE} ${DEST_IMAGE}
