sudo: required
services: docker
language: python
install:
  - pip install docker git+https://github.com/ansible/molecule.git openshift jmespath mcstatus
jobs:
  include:
  - name: Test role
    stage: test
    script: molecule test
  - name: Test local (Kubernetes)
    script: molecule test -s test-local
