sudo: required
services: docker
language: python
install:
  - pip install docker molecule openshift mcstatus
jobs:
  include:
  - name: Test role
    stage: test
    script: molecule test
  - name: Test local (Kubernetes)
    script: molecule test -s test-local
