---

- name: Set URL on status
  when: has_route
  k8s_status:
    api_version: apps.fabianism.us/v1alpha1
    kind: Minecraft
    name: '{{ meta.name }}'
    namespace: '{{ meta.namespace }}'
    status:
      url: "http://{{ q('k8s',
        api_version='route.openshift.io/v1',
        kind='Route',
        namespace=meta.namespace,
        resource_name='minecraft'
      ).0.spec.host }}"

- name: Set URL on status
  when: not has_route
  k8s_status:
    api_version: apps.fabianism.us/v1alpha1
    kind: Minecraft
    name: '{{ meta.name }}'
    namespace: '{{ meta.namespace }}'
    status:
      url: "http://{{ host_ip }}:{{ node_port }}"
  vars:
    host_ip: "{{ q('k8s',
      api_version='v1',
      kind='Pod',
      namespace=meta.namespace,
      label_selector='app=minecraft'
    ).0.status.hostIP }}"
    node_port: "{{ q('k8s',
      api_version='v1',
      kind='Service',
      namespace=meta.namespace,
      resource_name='minecraft'
    ).0.spec.ports.0.nodePort }}"
