---

- name: Fail early if EULA is not accepted
  fail:
    msg: "You must accept the EULA to run a Minecraft server"
  when: not minecraft_eula_accepted

- name: Create required resources for storage
  k8s:
    namespace: '{{ minecraft_namespace }}'
    definition: '{{ item }}'
  with_items: '{{ minecraft_persistent_volume_claims }}'

- name: Create Deployment
  k8s:
    namespace: '{{ minecraft_namespace }}'
    definition: '{{ lookup("template", "deployment.yaml.j2") | from_yaml }}'

- name: Create Service
  k8s:
    namespace: '{{ minecraft_namespace }}'
    definition: '{{ lookup("template", "service.yaml.j2") | from_yaml }}'
