---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" molecule roles reconcile.yml
  ansible-lint
platforms:
  - name: kind-default
    groups:
      - k8s
    image: bsycorp/kind:latest-${KUBE_VERSION:-1.16}
    privileged: True
    override_command: no
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-9443}:8443/tcp
      - 0.0.0.0:${MINECRAFT_NODE_PORT:-32176}:32176/tcp
    pre_build_image: yes
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        kubeconfig_file: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
        minecraft_eula_accepted: True
        minecraft_namespace: ${TEST_NAMESPACE:-osdk-test}
        minecraft_node_port: 32176
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
  env:
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-9443}'
scenario:
  name: default
verifier:
  name: ansible
