---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  roles:
    - minecraft

- import_playbook: asserts.yml
  vars:
    # address: "{{ q('k8s',
    #   api_version='v1',
    #   kind='Pod',
    #   namespace=namespace,
    #   label_selector='app=example-minecraft'
    # ).0.status.hostIP }}:{{ q('k8s',
    #   api_version='v1',
    #   kind='Service',
    #   namespace=namespace,
    #   label_selector='app=example-minecraft'
    # ).0.spec.ports.0.nodePort }}"
    meta:
      name: example-minecraft
      namespace: '{{ namespace }}'
