---
- name: Verify
  hosts: localhost
  connection: local
  tasks:
    - name: Wait two minutes to confirm server is reachable
      command: 'mcstatus {{ address }} ping'
      changed_when: false
      retries: 24
      delay: 5
      register: result
      until: not (result is failed)

    - name: Fetch status of server
      command: 'mcstatus {{ address }} status'
      changed_when: false
      register: mcstatus

    - name: Output status of server
      debug:
        var: mcstatus.stdout_lines
